import { supabase } from '@/lib/supabase/client';
import { requireUserId, getCurrentUserId } from './auth-utils';
import type { Event, Signup } from '@/types/domain';

const MAX_USER_EVENT_PARTICIPANTS = 20;

export interface CreateUserEventInput {
  name: string;
  description?: string | null;
  start_time: string;
  end_time: string;
  max_participants: number;
  cover_image?: string | null;
}

/**
 * Create a small event as a regular user (max 5 participants).
 */
export async function createUserEvent(input: CreateUserEventInput): Promise<Event> {
  if (input.max_participants > MAX_USER_EVENT_PARTICIPANTS) {
    throw new Error(`小型活动最多 ${MAX_USER_EVENT_PARTICIPANTS} 人`);
  }
  if (input.max_participants < 2) {
    throw new Error('至少需要 2 人');
  }

  const userId = await requireUserId();

  const { data, error } = await supabase
    .from('evt_events')
    .insert({
      name: input.name,
      description: input.description || null,
      start_time: input.start_time,
      end_time: input.end_time,
      max_participants: input.max_participants,
      cover_image: input.cover_image || null,
      created_by: userId,
    })
    .select('*')
    .single();

  if (error) throw error;

  // Auto-signup the creator
  await supabase.from('evt_signups').upsert(
    { event_id: data.event_id, user_id: userId, status: 'active' },
    { onConflict: 'event_id,user_id' }
  );

  return data;
}

/**
 * Get events created by the current user.
 */
export async function getMyCreatedEvents(): Promise<Event[]> {
  const userId = await getCurrentUserId();
  if (!userId) return [];

  const { data, error } = await supabase
    .from('evt_events')
    .select('*')
    .eq('created_by', userId)
    .order('start_time', { ascending: false });

  if (error) {
    console.error('Failed to load user events:', error);
    return [];
  }
  return data || [];
}

/**
 * Update a user-created event.
 */
export async function updateUserEvent(
  eventId: string,
  updates: Partial<Pick<Event, 'name' | 'description' | 'start_time' | 'end_time' | 'cover_image' | 'status' | 'max_participants'>>
): Promise<Event> {
  if (updates.max_participants != null && updates.max_participants > MAX_USER_EVENT_PARTICIPANTS) {
    throw new Error(`小型活动最多 ${MAX_USER_EVENT_PARTICIPANTS} 人`);
  }

  const { data, error } = await supabase
    .from('evt_events')
    .update(updates)
    .eq('event_id', eventId)
    .select('*')
    .single();

  if (error) throw error;
  return data;
}

/**
 * Delete a user-created event.
 */
export async function deleteUserEvent(eventId: string): Promise<void> {
  const { error } = await supabase
    .from('evt_events')
    .delete()
    .eq('event_id', eventId);

  if (error) throw error;
}

/**
 * Get signups for a user-created event (with profiles).
 */
export async function getUserEventParticipants(eventId: string): Promise<Signup[]> {
  const { data: signups, error } = await supabase
    .from('evt_signups')
    .select('signup_id, event_id, user_id, status, created_at, checked_in, checked_in_at')
    .eq('event_id', eventId)
    .eq('status', 'active')
    .order('created_at', { ascending: true });

  if (error || !signups) return [];

  const userIds = signups.map((s) => s.user_id);
  if (userIds.length === 0) return [];

  const { data: profiles } = await supabase
    .from('usr_profiles')
    .select('*')
    .in('user_id', userIds);

  const profileMap = new Map(
    (profiles || []).map((p) => [p.user_id, p])
  );

  return signups.map((s) => ({
    ...s,
    checked_in: s.checked_in || false,
    profile: profileMap.get(s.user_id),
  }));
}

/**
 * Invite a user by sharing the event code.
 * The event code is auto-generated by the database trigger.
 */
export async function getEventShareCode(eventId: string): Promise<string | null> {
  const { data, error } = await supabase
    .from('evt_events')
    .select('event_code')
    .eq('event_id', eventId)
    .single();

  if (error) return null;
  return data?.event_code ?? null;
}

/**
 * Remove a participant from a user-created event.
 */
export async function removeParticipant(eventId: string, userId: string): Promise<boolean> {
  const { error } = await supabase
    .from('evt_signups')
    .update({ status: 'cancelled' })
    .eq('event_id', eventId)
    .eq('user_id', userId);

  if (error) {
    console.error('Failed to remove participant:', error);
    return false;
  }
  return true;
}
