-- 注意：此文件已被后续迁移修改，表名已添加领域前缀
-- 请参考 20260129000000_rename_tables_with_domain_prefix.sql 了解最新表结构

  create table "public"."area" (
    "area_id" uuid not null default gen_random_uuid(),
    "venue_id" uuid not null,
    "name" text not null,
    "max_people" integer not null,
    "min_people" integer not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."area" enable row level security;


  create table "public"."event" (
    "event_id" uuid not null default gen_random_uuid(),
    "venue_id" uuid not null,
    "name" text not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."event" enable row level security;


  create table "public"."session" (
    "session_id" uuid not null default gen_random_uuid(),
    "event_id" uuid not null,
    "name" text not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."session" enable row level security;


  create table "public"."session_area" (
    "session_id" uuid not null,
    "area_id" uuid not null,
    "is_enabled" boolean default true
      );


alter table "public"."session_area" enable row level security;


  create table "public"."session_assignment" (
    "session_id" uuid not null,
    "user_id" uuid not null,
    "area_id" uuid not null,
    "checked_in" boolean default false,
    "is_applied" boolean default false,
    "assigned_by" text not null,
    "assigned_at" timestamp with time zone default now()
      );


alter table "public"."session_assignment" enable row level security;


  create table "public"."user_preferences" (
    "id" bigint generated by default as identity not null,
    "created_at" text not null,
    "user_id" uuid default gen_random_uuid(),
    "languages" text,
    "interests" text,
    "purpose" text,
    "industry_background" text
      );


alter table "public"."user_preferences" enable row level security;


  create table "public"."user_profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "nickname" text,
    "gender" text,
    "age_group" text
      );


alter table "public"."user_profiles" enable row level security;


  create table "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "role" text
      );


alter table "public"."user_roles" enable row level security;


  create table "public"."venue" (
    "venue_id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "capacity" integer not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."venue" enable row level security;

CREATE UNIQUE INDEX area_pkey ON public.area USING btree (area_id);

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (event_id);

CREATE INDEX idx_session_assignment_area ON public.session_assignment USING btree (session_id, area_id);

CREATE INDEX idx_session_assignment_checked_in ON public.session_assignment USING btree (session_id, checked_in);

CREATE UNIQUE INDEX session_area_pkey ON public.session_area USING btree (session_id, area_id);

CREATE UNIQUE INDEX session_assignment_pkey ON public.session_assignment USING btree (session_id, user_id);

CREATE UNIQUE INDEX session_pkey ON public.session USING btree (session_id);

CREATE UNIQUE INDEX user_preferences_pkey ON public.user_preferences USING btree (id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);

CREATE UNIQUE INDEX user_roles_user_id_key ON public.user_roles USING btree (user_id);

CREATE UNIQUE INDEX venue_pkey ON public.venue USING btree (venue_id);

alter table "public"."area" add constraint "area_pkey" PRIMARY KEY using index "area_pkey";

alter table "public"."event" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";

alter table "public"."session" add constraint "session_pkey" PRIMARY KEY using index "session_pkey";

alter table "public"."session_area" add constraint "session_area_pkey" PRIMARY KEY using index "session_area_pkey";

alter table "public"."session_assignment" add constraint "session_assignment_pkey" PRIMARY KEY using index "session_assignment_pkey";

alter table "public"."user_preferences" add constraint "user_preferences_pkey" PRIMARY KEY using index "user_preferences_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."venue" add constraint "venue_pkey" PRIMARY KEY using index "venue_pkey";

alter table "public"."area" add constraint "area_venue_id_fkey" FOREIGN KEY (venue_id) REFERENCES public.venue(venue_id) ON DELETE CASCADE not valid;

alter table "public"."area" validate constraint "area_venue_id_fkey";

alter table "public"."event" add constraint "event_venue_id_fkey" FOREIGN KEY (venue_id) REFERENCES public.venue(venue_id) ON DELETE CASCADE not valid;

alter table "public"."event" validate constraint "event_venue_id_fkey";

alter table "public"."session" add constraint "session_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.event(event_id) ON DELETE CASCADE not valid;

alter table "public"."session" validate constraint "session_event_id_fkey";

alter table "public"."session_area" add constraint "session_area_area_id_fkey" FOREIGN KEY (area_id) REFERENCES public.area(area_id) ON DELETE CASCADE not valid;

alter table "public"."session_area" validate constraint "session_area_area_id_fkey";

alter table "public"."session_area" add constraint "session_area_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.session(session_id) ON DELETE CASCADE not valid;

alter table "public"."session_area" validate constraint "session_area_session_id_fkey";

alter table "public"."session_assignment" add constraint "session_assignment_area_id_fkey" FOREIGN KEY (area_id) REFERENCES public.area(area_id) not valid;

alter table "public"."session_assignment" validate constraint "session_assignment_area_id_fkey";

alter table "public"."session_assignment" add constraint "session_assignment_assigned_by_check" CHECK ((assigned_by = ANY (ARRAY['host'::text, 'system'::text]))) not valid;

alter table "public"."session_assignment" validate constraint "session_assignment_assigned_by_check";

alter table "public"."session_assignment" add constraint "session_assignment_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.session(session_id) ON DELETE CASCADE not valid;

alter table "public"."session_assignment" validate constraint "session_assignment_session_id_fkey";

alter table "public"."user_preferences" add constraint "user_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_preferences" validate constraint "user_preferences_user_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_user_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_user_id_key" UNIQUE using index "user_roles_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_user_role(user_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  user_role TEXT;
BEGIN
  SELECT role INTO user_role FROM public.user_roles WHERE user_id = $1 LIMIT 1;
  RETURN COALESCE(user_role, 'user');
END;
$function$
;

grant delete on table "public"."area" to "anon";

grant insert on table "public"."area" to "anon";

grant references on table "public"."area" to "anon";

grant select on table "public"."area" to "anon";

grant trigger on table "public"."area" to "anon";

grant truncate on table "public"."area" to "anon";

grant update on table "public"."area" to "anon";

grant delete on table "public"."area" to "authenticated";

grant insert on table "public"."area" to "authenticated";

grant references on table "public"."area" to "authenticated";

grant select on table "public"."area" to "authenticated";

grant trigger on table "public"."area" to "authenticated";

grant truncate on table "public"."area" to "authenticated";

grant update on table "public"."area" to "authenticated";

grant delete on table "public"."area" to "postgres";

grant insert on table "public"."area" to "postgres";

grant references on table "public"."area" to "postgres";

grant select on table "public"."area" to "postgres";

grant trigger on table "public"."area" to "postgres";

grant truncate on table "public"."area" to "postgres";

grant update on table "public"."area" to "postgres";

grant delete on table "public"."area" to "service_role";

grant insert on table "public"."area" to "service_role";

grant references on table "public"."area" to "service_role";

grant select on table "public"."area" to "service_role";

grant trigger on table "public"."area" to "service_role";

grant truncate on table "public"."area" to "service_role";

grant update on table "public"."area" to "service_role";

grant delete on table "public"."event" to "anon";

grant insert on table "public"."event" to "anon";

grant references on table "public"."event" to "anon";

grant select on table "public"."event" to "anon";

grant trigger on table "public"."event" to "anon";

grant truncate on table "public"."event" to "anon";

grant update on table "public"."event" to "anon";

grant delete on table "public"."event" to "authenticated";

grant insert on table "public"."event" to "authenticated";

grant references on table "public"."event" to "authenticated";

grant select on table "public"."event" to "authenticated";

grant trigger on table "public"."event" to "authenticated";

grant truncate on table "public"."event" to "authenticated";

grant update on table "public"."event" to "authenticated";

grant delete on table "public"."event" to "postgres";

grant insert on table "public"."event" to "postgres";

grant references on table "public"."event" to "postgres";

grant select on table "public"."event" to "postgres";

grant trigger on table "public"."event" to "postgres";

grant truncate on table "public"."event" to "postgres";

grant update on table "public"."event" to "postgres";

grant delete on table "public"."event" to "service_role";

grant insert on table "public"."event" to "service_role";

grant references on table "public"."event" to "service_role";

grant select on table "public"."event" to "service_role";

grant trigger on table "public"."event" to "service_role";

grant truncate on table "public"."event" to "service_role";

grant update on table "public"."event" to "service_role";

grant delete on table "public"."session" to "anon";

grant insert on table "public"."session" to "anon";

grant references on table "public"."session" to "anon";

grant select on table "public"."session" to "anon";

grant trigger on table "public"."session" to "anon";

grant truncate on table "public"."session" to "anon";

grant update on table "public"."session" to "anon";

grant delete on table "public"."session" to "authenticated";

grant insert on table "public"."session" to "authenticated";

grant references on table "public"."session" to "authenticated";

grant select on table "public"."session" to "authenticated";

grant trigger on table "public"."session" to "authenticated";

grant truncate on table "public"."session" to "authenticated";

grant update on table "public"."session" to "authenticated";

grant delete on table "public"."session" to "postgres";

grant insert on table "public"."session" to "postgres";

grant references on table "public"."session" to "postgres";

grant select on table "public"."session" to "postgres";

grant trigger on table "public"."session" to "postgres";

grant truncate on table "public"."session" to "postgres";

grant update on table "public"."session" to "postgres";

grant delete on table "public"."session" to "service_role";

grant insert on table "public"."session" to "service_role";

grant references on table "public"."session" to "service_role";

grant select on table "public"."session" to "service_role";

grant trigger on table "public"."session" to "service_role";

grant truncate on table "public"."session" to "service_role";

grant update on table "public"."session" to "service_role";

grant delete on table "public"."session_area" to "anon";

grant insert on table "public"."session_area" to "anon";

grant references on table "public"."session_area" to "anon";

grant select on table "public"."session_area" to "anon";

grant trigger on table "public"."session_area" to "anon";

grant truncate on table "public"."session_area" to "anon";

grant update on table "public"."session_area" to "anon";

grant delete on table "public"."session_area" to "authenticated";

grant insert on table "public"."session_area" to "authenticated";

grant references on table "public"."session_area" to "authenticated";

grant select on table "public"."session_area" to "authenticated";

grant trigger on table "public"."session_area" to "authenticated";

grant truncate on table "public"."session_area" to "authenticated";

grant update on table "public"."session_area" to "authenticated";

grant delete on table "public"."session_area" to "postgres";

grant insert on table "public"."session_area" to "postgres";

grant references on table "public"."session_area" to "postgres";

grant select on table "public"."session_area" to "postgres";

grant trigger on table "public"."session_area" to "postgres";

grant truncate on table "public"."session_area" to "postgres";

grant update on table "public"."session_area" to "postgres";

grant delete on table "public"."session_area" to "service_role";

grant insert on table "public"."session_area" to "service_role";

grant references on table "public"."session_area" to "service_role";

grant select on table "public"."session_area" to "service_role";

grant trigger on table "public"."session_area" to "service_role";

grant truncate on table "public"."session_area" to "service_role";

grant update on table "public"."session_area" to "service_role";

grant delete on table "public"."session_assignment" to "anon";

grant insert on table "public"."session_assignment" to "anon";

grant references on table "public"."session_assignment" to "anon";

grant select on table "public"."session_assignment" to "anon";

grant trigger on table "public"."session_assignment" to "anon";

grant truncate on table "public"."session_assignment" to "anon";

grant update on table "public"."session_assignment" to "anon";

grant delete on table "public"."session_assignment" to "authenticated";

grant insert on table "public"."session_assignment" to "authenticated";

grant references on table "public"."session_assignment" to "authenticated";

grant select on table "public"."session_assignment" to "authenticated";

grant trigger on table "public"."session_assignment" to "authenticated";

grant truncate on table "public"."session_assignment" to "authenticated";

grant update on table "public"."session_assignment" to "authenticated";

grant delete on table "public"."session_assignment" to "postgres";

grant insert on table "public"."session_assignment" to "postgres";

grant references on table "public"."session_assignment" to "postgres";

grant select on table "public"."session_assignment" to "postgres";

grant trigger on table "public"."session_assignment" to "postgres";

grant truncate on table "public"."session_assignment" to "postgres";

grant update on table "public"."session_assignment" to "postgres";

grant delete on table "public"."session_assignment" to "service_role";

grant insert on table "public"."session_assignment" to "service_role";

grant references on table "public"."session_assignment" to "service_role";

grant select on table "public"."session_assignment" to "service_role";

grant trigger on table "public"."session_assignment" to "service_role";

grant truncate on table "public"."session_assignment" to "service_role";

grant update on table "public"."session_assignment" to "service_role";

grant delete on table "public"."user_preferences" to "anon";

grant insert on table "public"."user_preferences" to "anon";

grant references on table "public"."user_preferences" to "anon";

grant select on table "public"."user_preferences" to "anon";

grant trigger on table "public"."user_preferences" to "anon";

grant truncate on table "public"."user_preferences" to "anon";

grant update on table "public"."user_preferences" to "anon";

grant delete on table "public"."user_preferences" to "authenticated";

grant insert on table "public"."user_preferences" to "authenticated";

grant references on table "public"."user_preferences" to "authenticated";

grant select on table "public"."user_preferences" to "authenticated";

grant trigger on table "public"."user_preferences" to "authenticated";

grant truncate on table "public"."user_preferences" to "authenticated";

grant update on table "public"."user_preferences" to "authenticated";

grant delete on table "public"."user_preferences" to "postgres";

grant insert on table "public"."user_preferences" to "postgres";

grant references on table "public"."user_preferences" to "postgres";

grant select on table "public"."user_preferences" to "postgres";

grant trigger on table "public"."user_preferences" to "postgres";

grant truncate on table "public"."user_preferences" to "postgres";

grant update on table "public"."user_preferences" to "postgres";

grant delete on table "public"."user_preferences" to "service_role";

grant insert on table "public"."user_preferences" to "service_role";

grant references on table "public"."user_preferences" to "service_role";

grant select on table "public"."user_preferences" to "service_role";

grant trigger on table "public"."user_preferences" to "service_role";

grant truncate on table "public"."user_preferences" to "service_role";

grant update on table "public"."user_preferences" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "postgres";

grant insert on table "public"."user_profiles" to "postgres";

grant references on table "public"."user_profiles" to "postgres";

grant select on table "public"."user_profiles" to "postgres";

grant trigger on table "public"."user_profiles" to "postgres";

grant truncate on table "public"."user_profiles" to "postgres";

grant update on table "public"."user_profiles" to "postgres";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "postgres";

grant insert on table "public"."user_roles" to "postgres";

grant references on table "public"."user_roles" to "postgres";

grant select on table "public"."user_roles" to "postgres";

grant trigger on table "public"."user_roles" to "postgres";

grant truncate on table "public"."user_roles" to "postgres";

grant update on table "public"."user_roles" to "postgres";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";

grant delete on table "public"."venue" to "anon";

grant insert on table "public"."venue" to "anon";

grant references on table "public"."venue" to "anon";

grant select on table "public"."venue" to "anon";

grant trigger on table "public"."venue" to "anon";

grant truncate on table "public"."venue" to "anon";

grant update on table "public"."venue" to "anon";

grant delete on table "public"."venue" to "authenticated";

grant insert on table "public"."venue" to "authenticated";

grant references on table "public"."venue" to "authenticated";

grant select on table "public"."venue" to "authenticated";

grant trigger on table "public"."venue" to "authenticated";

grant truncate on table "public"."venue" to "authenticated";

grant update on table "public"."venue" to "authenticated";

grant delete on table "public"."venue" to "postgres";

grant insert on table "public"."venue" to "postgres";

grant references on table "public"."venue" to "postgres";

grant select on table "public"."venue" to "postgres";

grant trigger on table "public"."venue" to "postgres";

grant truncate on table "public"."venue" to "postgres";

grant update on table "public"."venue" to "postgres";

grant delete on table "public"."venue" to "service_role";

grant insert on table "public"."venue" to "service_role";

grant references on table "public"."venue" to "service_role";

grant select on table "public"."venue" to "service_role";

grant trigger on table "public"."venue" to "service_role";

grant truncate on table "public"."venue" to "service_role";

grant update on table "public"."venue" to "service_role";


  create policy "Allow users to insert their role"
  on "public"."user_roles"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Allow users to read their role"
  on "public"."user_roles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



